grails-app/domain/gshop/order/Order.groovy
package gshop.order

import org.apache.commons.codec.binary.Base32
import gshop.Address

import gshop.basket.Price
import gshop.security.BusinessCustomer
import gshop.security.Customer
import gshop.security.PrivateCustomer

class Order {

	static hasMany = [products: OrderProduct]

	Date dateCreated

	String uid;

	String shipmentMethodTitle
	BigDecimal shipmentMethodPrice

	String paymentMethodTitle
	BigDecimal paymentMethodPrice

	Price price

	Address deliveryAddress

	Address billingAddress

	OrderCustomer customer

	int orderNumber

	OrderState state

	boolean paymentReceived

	int productCount = 0

	static embedded = ['price', 'deliveryAddress', 'billingAddress', 'customer']

	static constraints = {
		deliveryAddress nullable: true
		shipmentMethodTitle nullable: true
		shipmentMethodPrice nullable: true
		paymentMethodTitle nullable: true
		paymentMethodPrice nullable: true
		uid maxSize: 50
	}

	static mapping = {
		table "gsorder"
	}

	Order saveOrder() {
		Integer largestOrderNumber = executeQuery("SELECT MAX(orderNumber) FROM Order")[0] as Integer
		if (largestOrderNumber == null) largestOrderNumber = 1;
		orderNumber = largestOrderNumber + 1
		Random rnd = new Random(orderNumber)

		boolean unique = false
		while (!unique) {
			byte[] bytes = new byte[5]
			rnd.nextBytes(bytes)
			uid = new Base32(false).encodeToString(bytes)
			if (executeQuery("SELECT COUNT(id) FROM Order WHERE uid = :uid", [uid: uid])[0] == 0) {
				unique = true
			}
		}
		return save(failOnError: true)
	}
}

class OrderCustomer {

	String username
	String email
	String phoneNumber

	String companyName
	String taxId
	String companyId
	String vat
	String contactPerson

	String firstName
	String lastName

	static constraints = {
		phoneNumber nullable: true, maxSize: 80
		email maxSize: 80
		username size: 5..80

		companyName maxSize: 50, nullable: true
		taxId maxSize: 30, nullable: true
		vat maxSize: 30, nullable: true
		companyId maxSize: 30, nullable: true
		contactPerson maxSize: 100, nullable: true

		firstName maxSize: 50, nullable: true
		lastName maxSize: 50, nullable: true
	}

	static OrderCustomer fromCustomer(Customer customer) {
		OrderCustomer orderCustomer = new OrderCustomer()
		orderCustomer.with {
			username = customer.username
			email = customer.email
			phoneNumber = customer.phoneNumber

			if (customer instanceof BusinessCustomer) {
				companyName = customer.companyName
				taxId = customer.taxId
				companyId = customer.companyId
				vat = customer.vat
				contactPerson = customer.contactPerson
			}

			if (customer instanceof PrivateCustomer) {
				firstName = customer.firstName
				lastName = customer.lastName
			}
		}
		return orderCustomer
	}
}

grails-app/domain/gshop/order/OrderProduct.groovy
package gshop.order


import gshop.basket.Price

class OrderProduct {

	static belongsTo = Order

	String code

	String title

	Price price

	Integer amount

	String imageExtension

	static embedded = ['price']

}

grails-app/domain/gshop/order/PaymentMethod.groovy
package gshop.order

import gshop.LocalizedString
import gshop.basket.Price

class PaymentMethod {

	static hasMany = [name: LocalizedString]

	BigDecimal price

	Price calculatedPrice

	String uid = UUID.randomUUID().toString()

	static transients = ['calculatedPrice']

	static constraints = {
		uid nullable: true, size: 36..36
	}
}

grails-app/domain/gshop/order/ShipmentMethod.groovy
package gshop.order

import gshop.LocalizedString
import gshop.basket.Price

class ShipmentMethod {

	static hasMany = [name: LocalizedString]

	BigDecimal price

	Price calculatedPrice

	String uid = UUID.randomUUID().toString()

	static transients = ['calculatedPrice']

	static constraints = {
		uid nullable: true, size: 36..36
	}
}

grails-app/domain/gshop/order/ValidPaymentShipmentCombination.groovy
package gshop.order

class ValidPaymentShipmentCombination {

	PaymentMethod paymentMethod

	ShipmentMethod shipmentMethod
}

grails-app/controllers/gshop/order/OrderController.groovy
package gshop.order

import grails.converters.JSON
import gshop.ClientDataTransformer
import gshop.basket.Basket
import gshop.basket.BasketItem
import gshop.basket.BasketService
import gshop.basket.Price
import gshop.product.ObjectImageType
import gshop.security.Customer
import gshop.security.UserService
import gshop.shop.PricingService
import org.springframework.beans.factory.annotation.Value
import org.springframework.web.servlet.support.RequestContextUtils

class OrderController {

	PricingService pricingService

	BasketService basketService

	UserService userService

	OrderService orderService

	ClientDataTransformer clientDataTransformer

	@Value('${shop.vat}')
	BigDecimal vat

	def placeOrder() {
		log.debug "Received request for new order"

		Basket basket = basketService.getCurrentBasket(session)
		Customer customer = userService.getCurrentCustomer()
		if (customer == null) throw new IllegalStateException("No customer in session")
		if (basket == null) throw new IllegalStateException("Order placed with no basket active")
		if (!basket.basketItems) throw new IllegalArgumentException("Ordering with empty basket")
		if (!customer.deliveryAddresses) throw new IllegalStateException("Ordering without a delivery address")

		ShipmentMethod shipmentMethod = ShipmentMethod.findByUid(params.shipmentMethodId)
		if (shipmentMethod == null) throw new IllegalArgumentException("ShipmentMethod with uid '$orderData.shipmentMethod' not found")
		PaymentMethod paymentMethod = PaymentMethod.findByUid(params.paymentMethodId)
		if (paymentMethod == null) throw new IllegalArgumentException("PaymentMethod with uid '$orderData.paymentMethod' not found")

		pricingService.calculateBasketPrices(basket, getClientDataTransformer())
		Order order = orderService.placeOrder(basket, customer, shipmentMethod, paymentMethod, RequestContextUtils.getLocale(request))

		if (basket.id) basket.delete()
		session.basket = null

		render order.uid
	}

	def orderMethods() {
		def methods = [:]
		methods.shipmentMethods = ShipmentMethod.list().collect { sm ->
			Price price = pricingService.calculateShipmentMethodPrice(sm, basketService.getCurrentBasket(session))
			return getClientDataTransformer().transformShipmentMethod(sm)
		}
		methods.paymentMethods = PaymentMethod.list().collect { pm ->
			Price price = pricingService.calculatePaymentMethodPrice(pm, basketService.getCurrentBasket(session))
			return getClientDataTransformer().transformPaymentMethod(pm)
		}
		methods.validCombinations = ValidPaymentShipmentCombination.list().collect { combo ->
			[
					paymentMethod: combo.paymentMethod.uid,
					shipmentMethod: combo.shipmentMethod.uid
			]
		}
		render methods as JSON
	}


	def summary() {
		log.debug "Received request for order summary"

		Basket basket = basketService.getCurrentBasket(session)
		Customer customer = userService.getCurrentCustomer()
		if (customer == null) throw new IllegalStateException("No customer in session")
		if (basket == null) throw new IllegalStateException("Missing basket in session for creating order summary")
		if (!basket.basketItems) throw new IllegalArgumentException("Cannot render order summary with empty basket")

		ShipmentMethod shipmentMethod = ShipmentMethod.findByUid(params.shipmentMethodId)
		if (shipmentMethod == null) throw new IllegalArgumentException("ShipmentMethod with uid '$orderData.shipmentMethod' not found")
		PaymentMethod paymentMethod = PaymentMethod.findByUid(params.paymentMethodId)
		if (paymentMethod == null) throw new IllegalArgumentException("PaymentMethod with uid '$orderData.paymentMethod' not found")

		pricingService.calculateBasketPrices(basket, getClientDataTransformer())
		pricingService.calculateShipmentMethodPrice(shipmentMethod, basket)
		pricingService.calculatePaymentMethodPrice(paymentMethod, basket)
		Price finalPrice = pricingService.calculateOrderPrice(basket, shipmentMethod, paymentMethod)
		def orderSummary = [
				products: [
						amount: basket.basketItems.size(),
						price: getClientDataTransformer().renderPriceValue(basket.basketItems.sum { it.price.baseWithVat })
				],
				finalPrice: getClientDataTransformer().renderPrice(finalPrice),
				shipmentMethod: getClientDataTransformer().transformShipmentMethod(shipmentMethod),
				paymentMethod: getClientDataTransformer().transformPaymentMethod(paymentMethod),
				billingAddress: getClientDataTransformer().transformAddress(customer.getBillingAddress())
		]
		if (customer.deliveryAddress) {
			orderSummary.deliveryAddress = getClientDataTransformer().transformAddress(customer.deliveryAddress)
		}

		render orderSummary as JSON
	}

	def overview() {
		Customer customer = userService.getCurrentCustomer()
		if (customer == null) throw new IllegalStateException("No customer in session")

		def orders = Order.executeQuery("SELECT o FROM Order o WHERE o.customer.username = :username", [username: customer.username])

		def orderList = orders.collect { order ->
			[
					g.formatDate(date: order.dateCreated, type: "datetime", style: "SHORT"),
					order.uid,
					order.productCount,
					order.price.baseWithVat,
					[
							value: order.state.name(),
							text: g.message(code: 'order.state.' + order.state.name())
					]
			]
		}

		render orderList as JSON
	}

	def details() {
		Customer customer = userService.getCurrentCustomer()
		if (customer == null) throw new IllegalStateException("No customer in session")

		def order = Order.findByUid(params.orderId)
		if (order == null) throw new IllegalArgumentException("Cannot find order '${params.orderId}'")

		def result = [
				dateCreated: g.formatDate(date: order.dateCreated, type: "datetime", style: "SHORT"),
				uid: order.uid,
				shipmentMethodTitle: order.shipmentMethodTitle,
				shipmentMethodPrice: order.shipmentMethodPrice,
				paymentMethodTitle: order.paymentMethodTitle,
				paymentMethodPrice: order.paymentMethodPrice,
				discountInfo: "",
				billingAddress: getClientDataTransformer().transformAddress(order.billingAddress),
				state: [
						value: order.state.name(),
						text: g.message(code: 'order.state.' + order.state.name())
				],
				paymentReceived: g.message(code: order.paymentReceived.toString()),
				price: [
						base: order.price.base,
						vatPercent: order.price.vatPercent,
						vatAmount: order.price.vatAmount,
						baseWithVat: order.price.baseWithVat
				]
		]
		if (order.deliveryAddress) {
			result.deliveryAddress = getClientDataTransformer().transformAddress(order.deliveryAddress)
		}
		result.products = order.products.collect { prod ->
			[
					shop.objectImageUrl(object: prod, type: ObjectImageType.SMALL),
					prod.amount,
					prod.code,
					prod.title,
					prod.price.baseWithVat,
					""
			]
		}

		render result as JSON
	}

	private ClientDataTransformer getClientDataTransformer() {
		clientDataTransformer.grailsTagLib = g
		clientDataTransformer.shopTagLib = shop
		return clientDataTransformer
	}
}

grails-app/views/admin/order/edit.gsp
<%@ page import="gshop.order.Order" %>
<!doctype html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'order.label', default: 'Order')}"/>
	<title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
	<a href="#edit-order" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

	<div class="nav" role="navigation">
		<ul>
			<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
			<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
		</ul>
	</div>

	<div id="edit-order" class="content scaffold-edit" role="main">
		<h1><g:message code="default.edit.label" args="[entityName]"/></h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
		<g:hasErrors bean="${orderInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${orderInstance}" var="error">
					<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
							error="${error}"/></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<g:form method="post">
			<g:hiddenField name="id" value="${orderInstance?.id}"/>
			<g:hiddenField name="version" value="${orderInstance?.version}"/>
			<fieldset class="form">
				<g:render template="form"/>
			</fieldset>
			<fieldset class="buttons">
				<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}"/>
				<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate=""
				                onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
			</fieldset>
		</g:form>
	</div>
</body>
</html>

grails-app/views/admin/order/list.gsp
<%@ page import="gshop.order.OrderState; java.text.DecimalFormat; gshop.order.Order; org.springframework.web.servlet.support.RequestContextUtils as RCU" %>
<!doctype html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'order.label', default: 'Order')}"/>
	<title><g:message code="default.list.label" args="[entityName]"/></title>
	<r:require modules="catalog, orderManagement"/>
</head>

<body>
	<div id="list-order" class="content scaffold-list" role="main">
		<h1><g:message code="default.list.label" args="[entityName]"/></h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
		<g:form class="filter-panel">
			<table>
				%{--<tr>
					<td><g:message code="order.filter.date_from" default="Date from"/></td>
					<td><g:datePicker name="filter.date_from" precision="day"/></td>
				</tr>
				<tr>
					<td><g:message code="order.filter.date_to" default="Date to"/></td>
					<td><g:datePicker name="filter.date_to" precision="day"/></td>
				</tr>--}%
				<tr>
					<td><g:message code="order.filter.name" default="Name"/></td>
					<td><g:textField name="filter.name" value="${params['filter.name']}"/></td>
				</tr>
			</table>
			<g:submitButton name="list"/>
		</g:form>
		<table>
			<thead>
				<tr>
					<g:sortableColumn property="dateCreated" title="${message(code: 'order.dateCreated.label', default: 'Date Created')}"/>

					<g:sortableColumn property="orderNumber" title="${message(code: 'order.orderNumber.label', default: 'Order Number')}"/>

					<th><g:message code="order.uid.label" default="UID"/></th>

					<th><g:message code="order.customer.label" default="Customer"/></th>

					<th><g:message code="order.price.label" default="Price"/></th>

					<g:sortableColumn property="state" title="${message(code: 'order.state.label', default: 'State')}"/>

					<th></th>
				</tr>
			</thead>
			<tbody>
				<g:each in="${orderInstanceList}" status="i" var="orderInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

						<td><g:formatDate date="${orderInstance.dateCreated}" type="datetime" style="MEDIUM"/></td>

						<td><g:fieldValue field="orderNumber" bean="${orderInstance}"/></td>

						<td><g:fieldValue field="uid" bean="${orderInstance}"/></td>

						<g:if test="${orderInstance.customer.companyName}">
							<td>${orderInstance.customer.companyName}</td>
						</g:if>
						<g:else>
							<td>${orderInstance.customer.firstName} ${orderInstance.customer.lastName}</td>
						</g:else>

						<td>&euro; <g:formatNumber number="${orderInstance.price.baseWithVat}"/></td>

						<td><g:link action="show" id="${orderInstance.uid}"><g:message code="order.action.open" default="Open"/></g:link></td>

						<td>
							<g:hiddenField name="orderId" value="${orderInstance.uid}"/>
							<g:select name="orderState" from="${OrderState.values()}" value="${orderInstance.state}"/>
							<g:submitButton name="updateStateButton" value="${g.message(code: 'orderManagement.stateChange.submit', default: 'Update state')}"/>
						</td>
					</tr>
				</g:each>
			</tbody>
		</table>

		<div class="pagination">
			<g:paginate total="${orderInstanceTotal}"/>
		</div>
	</div>
</body>
</html>

grails-app/views/admin/order/show.gsp
<%@ page import="gshop.order.Order" %>
<!doctype html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'order.label', default: 'Order')}"/>
	<title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
	<a href="#show-order" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

	<div class="nav" role="navigation">
		<ul>
			<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
			<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]"/></g:link></li>
		</ul>
	</div>

	<div id="show-order" class="content scaffold-show" role="main">
		<h1><g:message code="default.show.label" args="[entityName]"/></h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
		</g:if>
		<ol class="property-list order">

			<g:if test="${orderInstance?.discountInfo}">
				<li class="fieldcontain">
					<span id="discountInfo-label" class="property-label"><g:message code="order.discountInfo.label" default="Discount Info"/></span>

					<span class="property-value" aria-labelledby="discountInfo-label"><g:fieldValue bean="${orderInstance}" field="discountInfo"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.billingAddress}">
				<li class="fieldcontain">
					<span id="billingAddress-label" class="property-label"><g:message code="order.billingAddress.label" default="Billing Address"/></span>

					<span class="property-value" aria-labelledby="billingAddress-label"><g:fieldValue bean="${orderInstance}" field="billingAddress"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.customer}">
				<li class="fieldcontain">
					<span id="customer-label" class="property-label"><g:message code="order.customer.label" default="Customer"/></span>

					<span class="property-value" aria-labelledby="customer-label"><g:fieldValue bean="${orderInstance}" field="customer"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="order.dateCreated.label" default="Date Created"/></span>

					<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${orderInstance?.dateCreated}"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.deliveryAddress}">
				<li class="fieldcontain">
					<span id="deliveryAddress-label" class="property-label"><g:message code="order.deliveryAddress.label" default="Delivery Address"/></span>

					<span class="property-value" aria-labelledby="deliveryAddress-label"><g:fieldValue bean="${orderInstance}" field="deliveryAddress"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.orderNumber}">
				<li class="fieldcontain">
					<span id="orderNumber-label" class="property-label"><g:message code="order.orderNumber.label" default="Order Number"/></span>

					<span class="property-value" aria-labelledby="orderNumber-label"><g:fieldValue bean="${orderInstance}" field="orderNumber"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.paymentMethodPrice}">
				<li class="fieldcontain">
					<span id="paymentMethodPrice-label" class="property-label"><g:message code="order.paymentMethodPrice.label"
					                                                                      default="Payment Method Price"/></span>

					<span class="property-value" aria-labelledby="paymentMethodPrice-label"><g:fieldValue bean="${orderInstance}"
					                                                                                      field="paymentMethodPrice"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.paymentMethodTitle}">
				<li class="fieldcontain">
					<span id="paymentMethodTitle-label" class="property-label"><g:message code="order.paymentMethodTitle.label"
					                                                                      default="Payment Method Title"/></span>

					<span class="property-value" aria-labelledby="paymentMethodTitle-label"><g:fieldValue bean="${orderInstance}"
					                                                                                      field="paymentMethodTitle"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.paymentReceived}">
				<li class="fieldcontain">
					<span id="paymentReceived-label" class="property-label"><g:message code="order.paymentReceived.label" default="Payment Received"/></span>

					<span class="property-value" aria-labelledby="paymentReceived-label"><g:formatBoolean boolean="${orderInstance?.paymentReceived}"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.price}">
				<li class="fieldcontain">
					<span id="price-label" class="property-label"><g:message code="order.price.label" default="Price"/></span>

					<span class="property-value" aria-labelledby="price-label"><g:fieldValue bean="${orderInstance}" field="price"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.products}">
				<li class="fieldcontain">
					<span id="products-label" class="property-label"><g:message code="order.products.label" default="Products"/></span>

					<g:each in="${orderInstance.products}" var="p">
						<span class="property-value" aria-labelledby="products-label"><g:link controller="orderProduct" action="show"
						                                                                      id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
					</g:each>

				</li>
			</g:if>

			<g:if test="${orderInstance?.shipmentMethodPrice}">
				<li class="fieldcontain">
					<span id="shipmentMethodPrice-label" class="property-label"><g:message code="order.shipmentMethodPrice.label"
					                                                                       default="Shipment Method Price"/></span>

					<span class="property-value" aria-labelledby="shipmentMethodPrice-label"><g:fieldValue bean="${orderInstance}"
					                                                                                       field="shipmentMethodPrice"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.shipmentMethodTitle}">
				<li class="fieldcontain">
					<span id="shipmentMethodTitle-label" class="property-label"><g:message code="order.shipmentMethodTitle.label"
					                                                                       default="Shipment Method Title"/></span>

					<span class="property-value" aria-labelledby="shipmentMethodTitle-label"><g:fieldValue bean="${orderInstance}"
					                                                                                       field="shipmentMethodTitle"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.state}">
				<li class="fieldcontain">
					<span id="state-label" class="property-label"><g:message code="order.state.label" default="State"/></span>

					<span class="property-value" aria-labelledby="state-label"><g:fieldValue bean="${orderInstance}" field="state"/></span>

				</li>
			</g:if>

			<g:if test="${orderInstance?.uid}">
				<li class="fieldcontain">
					<span id="uid-label" class="property-label"><g:message code="order.uid.label" default="Uid"/></span>

					<span class="property-value" aria-labelledby="uid-label"><g:fieldValue bean="${orderInstance}" field="uid"/></span>

				</li>
			</g:if>

		</ol>
		<g:form>
			<fieldset class="buttons">
				<g:hiddenField name="id" value="${orderInstance?.id}"/>
				<g:link class="edit" action="edit" id="${orderInstance?.id}"><g:message code="default.button.edit.label" default="Edit"/></g:link>
				<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}"
				                onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
			</fieldset>
		</g:form>
	</div>
</body>
</html>